require('plugin_configs.mason_lspconfig')
require('plugin_configs.neodev')
require('plugin_configs.nvim-cmp')
require('plugin_configs.nvim-tree')
require('plugin_configs.telescope')
require('plugin_configs.treesitter')
